CREATE USER postgrest WITH PASSWORD 'postgrest';
REVOKE ALL ON DATABASE postgres FROM postgrest;
GRANT CONNECT ON DATABASE postgres TO postgrest;
GRANT SELECT ON ALL TABLES IN SCHEMA w TO postgrest;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA w TO postgrest;
GRANT USAGE ON SCHEMA w TO postgrest;