CREATE FUNCTION W.STIMMZETTEL_ZWEITSTIMME(WAHLKREIS text) RETURNS TABLE(
	name text,
	partei text,
	wahlkreis text,
	listenplatz integer
) AS $$
SELECT K.NAME,
	K.PARTEI,
	K.LISTENKANDIDATINWAHLKREIS,
	K.LISTENPLATZ
FROM W.KANDIDAT K
	LEFT JOIN UNNEST(
		'{CSU,SPD,FREIE WÄHLER,GRÜNE,FDP,DIE LINKE,BP,ÖDP,PIRATEN,DIE FRANKEN,AfD,LKR,mut,Die Humanisten,Die PARTEI,Gesundheitsforschung,Tierschutzpartei,V-Partei³}'::text []
	) WITH ORDINALITY T(PARTEI, ORD) ON K.PARTEI = T.PARTEI
WHERE K.LANDTAGSWAHL = 2018
	AND K.LISTENKANDIDATINWAHLKREIS = WAHLKREIS
ORDER BY T.ORD,
	K.LISTENPLATZ $$ LANGUAGE SQL IMMUTABLE;