CREATE VIEW W.GEWAEHLTE(
	LANDTAGSWAHL,
	PERSNR,
	NAME,
	PARTEI,
	WAHLKREIS,
	STIMMKREIS,
	STIMMKREISNAME,
	TYP
) AS WITH ERSTSTIMMEN_KANDIDAT AS (
	SELECT KANDIDAT,
		LANDTAGSWAHL,
		COUNT(*) AS ANZAHL
	FROM W.ERSTSTIMME
	GROUP BY KANDIDAT,
		LANDTAGSWAHL
),
ZWEITSTIMMEN_KANDIDAT AS (
	SELECT KANDIDAT,
		LANDTAGSWAHL,
		COUNT(*) AS ANZAHL
	FROM W.ZWEITSTIMMEKANDIDAT
	GROUP BY KANDIDAT,
		LANDTAGSWAHL
),
GESAMTSTIMMEN_KANDIDAT AS (
	SELECT K.*,
		E.ANZAHL AS ERSTSTIMMEN,
		Z.ANZAHL AS ZWEITSTIMMEN,
		COALESCE(E.ANZAHL, 0) + COALESCE(Z.ANZAHL, 0) AS GESAMTSTIMMEN
	FROM W.KANDIDAT K
		LEFT JOIN ERSTSTIMMEN_KANDIDAT E ON K.PERSNR = E.KANDIDAT
		AND K.LANDTAGSWAHL = E.LANDTAGSWAHL
		LEFT JOIN ZWEITSTIMMEN_KANDIDAT Z ON K.PERSNR = Z.KANDIDAT
		AND K.LANDTAGSWAHL = Z.LANDTAGSWAHL
),
ERSTSTIMMEN_ORDNUNG AS (
	SELECT STIMMKREIS,
		WAHLKREIS,
		LANDTAGSWAHL,
		PERSNR,
		PARTEI,
		ANZAHL,
		(
			ROW_NUMBER() OVER(
				PARTITION BY LANDTAGSWAHL,
				STIMMKREIS
				ORDER BY ANZAHL DESC
			)
		)
	FROM W.ERSTSTIMMENPROKANDIDATSTIMMKREIS
),
GEWAEHLT_ERSTSTIMME AS (
	SELECT K.NAME,
		O.*
	FROM ERSTSTIMMEN_ORDNUNG O
		JOIN W.KANDIDAT K ON K.PERSNR = O.PERSNR
		AND K.LANDTAGSWAHL = O.LANDTAGSWAHL
	WHERE ROW_NUMBER = 1
),
GESAMTSTIMMEN_LISTEN_ORDNUNG AS (
	SELECT *,
		ROW_NUMBER() OVER (
			PARTITION BY LANDTAGSWAHL,
			PARTEI,
			LISTENKANDIDATINWAHLKREIS
			ORDER BY GESAMTSTIMMEN DESC
		)
	FROM GESAMTSTIMMEN_KANDIDAT
	WHERE (PERSNR, LANDTAGSWAHL) NOT IN (
			SELECT PERSNR,
				LANDTAGSWAHL
			FROM GEWAEHLT_ERSTSTIMME
		)
),
DIREKTMANDATE_PARTEI AS (
	SELECT LANDTAGSWAHL,
		PARTEI,
		WAHLKREIS,
		COUNT(*) AS ANZAHL
	FROM GEWAEHLT_ERSTSTIMME
	GROUP BY LANDTAGSWAHL,
		PARTEI,
		WAHLKREIS
),
LISTENMANDATE_PARTEI AS (
	SELECT S.LANDTAGSWAHL,
		S.PARTEI,
		S.WAHLKREIS,
		S.GESAMT - COALESCE(D.ANZAHL, 0) AS ANZAHL
	FROM W.SITZPLATZVERTEILUNG S
		LEFT JOIN DIREKTMANDATE_PARTEI D ON D.PARTEI = S.PARTEI
		AND D.WAHLKREIS = S.WAHLKREIS
		AND D.LANDTAGSWAHL = S.LANDTAGSWAHL
),
GEWAEHLT_LISTE AS (
	SELECT O.*
	FROM GESAMTSTIMMEN_LISTEN_ORDNUNG O
		JOIN LISTENMANDATE_PARTEI L ON O.LANDTAGSWAHL = L.LANDTAGSWAHL
		AND O.PARTEI = L.PARTEI
		AND O.LISTENKANDIDATINWAHLKREIS = L.WAHLKREIS
	WHERE ROW_NUMBER <= L.ANZAHL
),
ERGEBNIS AS (
	SELECT PERSNR,
		LANDTAGSWAHL,
		NAME,
		PARTEI,
		STIMMKREIS,
		WAHLKREIS,
		('Direktmandat') AS TYP
	FROM GEWAEHLT_ERSTSTIMME
	UNION
	SELECT PERSNR,
		LANDTAGSWAHL,
		NAME,
		PARTEI,
		NULL AS STIMMKREIS,
		LISTENKANDIDATINWAHLKREIS AS WAHLKREIS,
		('Listenmandat') AS TYP
	FROM GEWAEHLT_LISTE
)
SELECT E.LANDTAGSWAHL,
	E.PERSNR,
	E.NAME,
	E.PARTEI,
	E.WAHLKREIS,
	E.STIMMKREIS,
	S.STIMMKREISNAME,
	E.TYP
FROM ERGEBNIS E
	LEFT JOIN W.STIMMKREIS S ON S.NUMMER = E.STIMMKREIS
	AND S.LANDTAGSWAHL = E.LANDTAGSWAHL
ORDER BY NAME