version: '3'

services:
  server:
    image: postgrest/postgrest
    ports:
      - "3030:3000"
    networks:
      w:
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMA: w
      PGRST_DB_ANON_ROLE: postgres # In production this role should not be the same as the one used for the connection
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3030"
    depends_on:
      - db
  db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    networks:
      w:
    environment:
      POSTGRES_PASSWORD: postgres
    entrypoint: /override-docker-entrypoint.sh
    volumes:
      - "./database/Wahlinformationssystem-Schema.sql:/docker-entrypoint-initdb.d/00-init-schema.sql"
      - "./scripts/10-populate-db.sh:/docker-entrypoint-initdb.d/10-populate-db.sh"
      - "./database/VIEW_ErststimmenProKandidatUndStimmkreis.sql:/docker-entrypoint-initdb.d/20-create-view-erststimmenprokandidatundstimmkreis.sql"
      - "./database/VIEW_StimmenProWahlkreis.sql:/docker-entrypoint-initdb.d/30-create-view-stimmenprowahlkreis.sql"
      - "./database/VIEW_Sitzplatzverteilung.sql:/docker-entrypoint-initdb.d/40-create-view-sitzplatzverteilung.sql"
      - "./database/VIEW_StimmenProStimmkreis.sql:/docker-entrypoint-initdb.d/50-create-view-stimmenprostimmkreis.sql"
      - "./database/VIEW_StimmenProParteiStimmkreis.sql:/docker-entrypoint-initdb.d/60-create-view-stimmenproparteistimmkreis.sql"
      - "./database/VIEW_StimmkreisSiegerPartei.sql:/docker-entrypoint-initdb.d/70-create-view-stimmkreissiegerpartei.sql"
      - "./database/VIEW_StimmkreisVergleichVorjahr.sql:/docker-entrypoint-initdb.d/80-create-view-stimmkreisvergleichvorjahr.sql"
      - "./database:/database"
      - "./scripts/docker-entrypoint.sh:/override-docker-entrypoint.sh"
networks:
  w:
